server:
  port: 10010
zuul:
  routes:
    login-service: /login/**
  ignored-services:
      consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10000/eureka

spring:
  application:
    name: zuul-gateway